services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_USER: ash
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"