spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: ash
    password: pass123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
  application:
    name: shop-it
  docker:
    compose:
      enabled: false

message:
  api:
    url: https://api.message.com
    key: dSHUyu===
  docker:
    compose:
      enabled: false

